"""KJV / Apocrypha scripture texts for each feast-day reference."""

SCRIPTURE_TEXT: dict[str, str] = {
    # ── Passover ──────────────────────────────────────────────────────────
    "Leviticus 23:5": (
        "In the fourteenth day of the first month at even "
        "is the LORD's passover."
    ),
    "Exodus 12:1-14": (
        "And the LORD spake unto Moses and Aaron in the land of Egypt, saying, "
        "This month shall be unto you the beginning of months: it shall be the "
        "first month of the year to you. Speak ye unto all the congregation of "
        "Israel, saying, In the tenth day of this month they shall take to them "
        "every man a lamb, according to the house of their fathers, a lamb for "
        "an house: And if the household be too little for the lamb, let him and "
        "his neighbour next unto his house take it according to the number of "
        "the souls; every man according to his eating shall make your count for "
        "the lamb. Your lamb shall be without blemish, a male of the first "
        "year: ye shall take it out from the sheep, or from the goats: And ye "
        "shall keep it up until the fourteenth day of the same month: and the "
        "whole assembly of the congregation of Israel shall kill it in the "
        "evening. And they shall take of the blood, and strike it on the two "
        "side posts and on the upper door post of the houses, wherein they "
        "shall eat it. And they shall eat the flesh in that night, roast with "
        "fire, and unleavened bread; and with bitter herbs they shall eat it. "
        "Eat not of it raw, nor sodden at all with water, but roast with fire; "
        "his head with his legs, and with the purtenance thereof. And ye shall "
        "let nothing of it remain until the morning; and that which remaineth "
        "of it until the morning ye shall burn with fire. And thus shall ye "
        "eat it; with your loins girded, your shoes on your feet, and your "
        "staff in your hand; and ye shall eat it in haste: it is the LORD's "
        "passover. For I will pass through the land of Egypt this night, and "
        "will smite all the firstborn in the land of Egypt, both man and "
        "beast; and against all the gods of Egypt I will execute judgment: I "
        "am the LORD. And the blood shall be to you for a token upon the "
        "houses where ye are: and when I see the blood, I will pass over you, "
        "and the plague shall not be upon you to destroy you, when I smite the "
        "land of Egypt. And this day shall be unto you for a memorial; and ye "
        "shall keep it a feast to the LORD throughout your generations; ye "
        "shall keep it a feast by an ordinance for ever."
    ),

    # ── Unleavened Bread ──────────────────────────────────────────────────
    "Leviticus 23:6-8": (
        "And on the fifteenth day of the same month is the feast of unleavened "
        "bread unto the LORD: seven days ye must eat unleavened bread. In the "
        "first day ye shall have an holy convocation: ye shall do no servile "
        "work therein. But ye shall offer an offering made by fire unto the "
        "LORD seven days: in the seventh day is an holy convocation: ye shall "
        "do no servile work therein."
    ),
    "Exodus 12:15-20": (
        "Seven days shall ye eat unleavened bread; even the first day ye shall "
        "put away leaven out of your houses: for whosoever eateth leavened "
        "bread from the first day until the seventh day, that soul shall be "
        "cut off from Israel. And in the first day there shall be an holy "
        "convocation, and in the seventh day there shall be an holy "
        "convocation to you; no manner of work shall be done in them, save "
        "that which every man must eat, that only may be done of you. And ye "
        "shall observe the feast of unleavened bread; for in this selfsame day "
        "have I brought your armies out of the land of Egypt: therefore shall "
        "ye observe this day in your generations by an ordinance for ever. In "
        "the first month, on the fourteenth day of the month at even, ye shall "
        "eat unleavened bread, until the one and twentieth day of the month at "
        "even. Seven days shall there be no leaven found in your houses: for "
        "whosoever eateth that which is leavened, even that soul shall be cut "
        "off from the congregation of Israel, whether he be a stranger, or "
        "born in the land. Ye shall eat nothing leavened; in all your "
        "habitations shall ye eat unleavened bread."
    ),

    # ── Feast of Weeks (Shavuot / Pentecost) ─────────────────────────────
    "Leviticus 23:15-21": (
        "And ye shall count unto you from the morrow after the sabbath, from "
        "the day that ye brought the sheaf of the wave offering; seven "
        "sabbaths shall be complete: Even unto the morrow after the seventh "
        "sabbath shall ye number fifty days; and ye shall offer a new meat "
        "offering unto the LORD. Ye shall bring out of your habitations two "
        "wave loaves of two tenth deals: they shall be of fine flour; they "
        "shall be baken with leaven; they are the firstfruits unto the LORD. "
        "And ye shall offer with the bread seven lambs without blemish of the "
        "first year, and one young bullock, and two rams: they shall be for a "
        "burnt offering unto the LORD, with their meat offering, and their "
        "drink offerings, even an offering made by fire, of sweet savour unto "
        "the LORD. Then ye shall sacrifice one kid of the goats for a sin "
        "offering, and two lambs of the first year for a sacrifice of peace "
        "offerings. And the priest shall wave them with the bread of the "
        "firstfruits for a wave offering before the LORD, with the two lambs: "
        "they shall be holy to the LORD for the priest. And ye shall proclaim "
        "on the selfsame day, that it may be an holy convocation unto you: ye "
        "shall do no servile work therein: it shall be a statute for ever in "
        "all your dwellings throughout your generations."
    ),
    "Acts 2:1-4": (
        "And when the day of Pentecost was fully come, they were all with one "
        "accord in one place. And suddenly there came a sound from heaven as "
        "of a rushing mighty wind, and it filled all the house where they were "
        "sitting. And there appeared unto them cloven tongues like as of fire, "
        "and it sat upon each of them. And they were all filled with the Holy "
        "Ghost, and began to speak with other tongues, as the Spirit gave them "
        "utterance."
    ),

    # ── Feast of Trumpets ─────────────────────────────────────────────────
    "Leviticus 23:23-25": (
        "And the LORD spake unto Moses, saying, Speak unto the children of "
        "Israel, saying, In the seventh month, in the first day of the month, "
        "shall ye have a sabbath, a memorial of blowing of trumpets, an holy "
        "convocation. Ye shall do no servile work therein: but ye shall offer "
        "an offering made by fire unto the LORD."
    ),
    "Psalm 81:3": (
        "Blow up the trumpet in the new moon, in the time appointed, on our "
        "solemn feast day."
    ),

    # ── Day of Atonement ─────────────────────────────────────────────────
    "Leviticus 23:26-32": (
        "And the LORD spake unto Moses, saying, Also on the tenth day of this "
        "seventh month there shall be a day of atonement: it shall be an holy "
        "convocation unto you; and ye shall afflict your souls, and offer an "
        "offering made by fire unto the LORD. And ye shall do no work in that "
        "same day: for it is a day of atonement, to make an atonement for you "
        "before the LORD your God. For whatsoever soul it be that shall not be "
        "afflicted in that same day, he shall be cut off from among his "
        "people. And whatsoever soul it be that doeth any work in that same "
        "day, the same soul will I destroy from among his people. Ye shall do "
        "no manner of work: it shall be a statute for ever throughout your "
        "generations in all your dwellings. It shall be unto you a sabbath of "
        "rest, and ye shall afflict your souls: in the ninth day of the month "
        "at even, from even unto even, shall ye celebrate your sabbath."
    ),
    "Leviticus 16:29-34": (
        "And this shall be a statute for ever unto you: that in the seventh "
        "month, on the tenth day of the month, ye shall afflict your souls, "
        "and do no work at all, whether it be one of your own country, or a "
        "stranger that sojourneth among you: For on that day shall the priest "
        "make an atonement for you, to cleanse you, that ye may be clean from "
        "all your sins before the LORD. It shall be a sabbath of rest unto "
        "you, and ye shall afflict your souls, by a statute for ever. And the "
        "priest, whom he shall anoint, and whom he shall consecrate to "
        "minister in the priest's office in his father's stead, shall make "
        "the atonement, and shall put on the linen clothes, even the holy "
        "garments: And he shall make an atonement for the holy sanctuary, and "
        "he shall make an atonement for the tabernacle of the congregation, "
        "and for the altar, and he shall make an atonement for the priests, "
        "and for all the people of the congregation. And this shall be an "
        "everlasting statute unto you, to make an atonement for the children "
        "of Israel for all their sins once a year. And he did as the LORD "
        "commanded Moses."
    ),

    # ── Feast of Tabernacles ─────────────────────────────────────────────
    "Leviticus 23:33-43": (
        "And the LORD spake unto Moses, saying, Speak unto the children of "
        "Israel, saying, The fifteenth day of this seventh month shall be the "
        "feast of tabernacles for seven days unto the LORD. On the first day "
        "shall be an holy convocation: ye shall do no servile work therein. "
        "Seven days ye shall offer an offering made by fire unto the LORD: on "
        "the eighth day shall be an holy convocation unto you; and ye shall "
        "offer an offering made by fire unto the LORD: it is a solemn "
        "assembly; and ye shall do no servile work therein. These are the "
        "feasts of the LORD, which ye shall proclaim to be holy convocations, "
        "to offer an offering made by fire unto the LORD, a burnt offering, "
        "and a meat offering, a sacrifice, and drink offerings, every thing "
        "upon his day: Beside the sabbaths of the LORD, and beside your "
        "gifts, and beside all your vows, and beside all your freewill "
        "offerings, which ye give unto the LORD. Also in the fifteenth day of "
        "the seventh month, when ye have gathered in the fruit of the land, "
        "ye shall keep a feast unto the LORD seven days: on the first day "
        "shall be a sabbath, and on the eighth day shall be a sabbath. And ye "
        "shall take you on the first day the boughs of goodly trees, branches "
        "of palm trees, and the boughs of thick trees, and willows of the "
        "brook; and ye shall rejoice before the LORD your God seven days. And "
        "ye shall keep it a feast unto the LORD seven days in the year. It "
        "shall be a statute for ever in your generations: ye shall celebrate "
        "it in the seventh month. Ye shall dwell in booths seven days; all "
        "that are Israelites born shall dwell in booths: That your generations "
        "may know that I made the children of Israel to dwell in booths, when "
        "I brought them out of the land of Egypt: I am the LORD your God."
    ),
    "Zechariah 14:16-19": (
        "And it shall come to pass, that every one that is left of all the "
        "nations which came against Jerusalem shall even go up from year to "
        "year to worship the King, the LORD of hosts, and to keep the feast "
        "of tabernacles. And it shall be, that whoso will not come up of all "
        "the families of the earth unto Jerusalem to worship the King, the "
        "LORD of hosts, even upon them shall be no rain. And if the family of "
        "Egypt go not up, and come not, that have no rain; there shall be the "
        "plague, wherewith the LORD will smite the heathen that come not up "
        "to keep the feast of tabernacles. This shall be the punishment of "
        "Egypt, and the punishment of all nations that come not up to keep "
        "the feast of tabernacles."
    ),
    "John 7:37-38": (
        "In the last day, that great day of the feast, Jesus stood and cried, "
        "saying, If any man thirst, let him come unto me, and drink. He that "
        "believeth on me, as the scripture hath said, out of his belly shall "
        "flow rivers of living water."
    ),
    "2 Maccabees 10:6-8": (
        "And they kept eight days with gladness, as in the feast of the "
        "tabernacles, remembering that not long afore they had held the feast "
        "of the tabernacles, when as they wandered in the mountains and dens "
        "like beasts. Therefore they bare branches, and fair boughs, and palms "
        "also, and sang psalms unto him that had given them good success in "
        "cleansing his place. They ordained also by a common statute and "
        "decree, That every year those days should be kept of the whole nation "
        "of the Jews."
    ),

    # ── Purim ─────────────────────────────────────────────────────────────
    "Esther 9:20-32": (
        "And Mordecai wrote these things, and sent letters unto all the Jews "
        "that were in all the provinces of the king Ahasuerus, both nigh and "
        "far, To stablish this among them, that they should keep the "
        "fourteenth day of the month Adar, and the fifteenth day of the same, "
        "yearly, As the days wherein the Jews rested from their enemies, and "
        "the month which was turned unto them from sorrow to joy, and from "
        "mourning into a good day: that they should make them days of feasting "
        "and joy, and of sending portions one to another, and gifts to the "
        "poor. And the Jews undertook to do as they had begun, and as Mordecai "
        "had written unto them; Because Haman the son of Hammedatha, the "
        "Agagite, the enemy of all the Jews, had devised against the Jews to "
        "destroy them, and had cast Pur, that is, the lot, to consume them, "
        "and to destroy them; But when Esther came before the king, he "
        "commanded by letters that his wicked device, which he devised against "
        "the Jews, should return upon his own head, and that he and his sons "
        "should be hanged on the gallows. Wherefore they called these days "
        "Purim after the name of Pur. Therefore for all the words of this "
        "letter, and of that which they had seen concerning this matter, and "
        "which had come unto them, The Jews ordained, and took upon them, and "
        "upon their seed, and upon all such as joined themselves unto them, so "
        "as it should not fail, that they would keep these two days according "
        "to their writing, and according to their appointed time every year; "
        "And that these days should be remembered and kept throughout every "
        "generation, every family, every province, and every city; and that "
        "these days of Purim should not fail from among the Jews, nor the "
        "memorial of them perish from their seed. Then Esther the queen, the "
        "daughter of Abihail, and Mordecai the Jew, wrote with all authority, "
        "to confirm this second letter of Purim. And he sent the letters unto "
        "all the Jews, to the hundred twenty and seven provinces of the "
        "kingdom of Ahasuerus, with words of peace and truth, To confirm "
        "these days of Purim in their times appointed, according as Mordecai "
        "the Jew and Esther the queen had enjoined them, and as they had "
        "decreed for themselves and for their seed, the matters of the "
        "fastings and their cry. And the decree of Esther confirmed these "
        "matters of Purim; and it was written in the book."
    ),
    "2 Maccabees 15:36": (
        "And they ordained all with a common decree in no case to let that "
        "day pass without solemnity, but to celebrate the thirteenth day of "
        "the twelfth month, which in the Syrian tongue is called Adar, the "
        "day before Mardocheus' day."
    ),

    # ── Hanukkah (Feast of Dedication) ───────────────────────────────────
    "John 10:22-23": (
        "And it was at Jerusalem the feast of the dedication, and it was "
        "winter. And Jesus walked in the temple in Solomon's porch."
    ),
    "1 Maccabees 4:36-59": (
        "Then said Judas and his brethren, Behold, our enemies are "
        "discomfited: let us go up to cleanse and dedicate the sanctuary. "
        "Upon this all the host assembled themselves together, and went up "
        "into mount Sion. And when they saw the sanctuary desolate, and the "
        "altar profaned, and the gates burned up, and shrubs growing in the "
        "courts as in a forest, or in one of the mountains, yea, and the "
        "priests' chambers pulled down; They rent their clothes, and made "
        "great lamentation, and cast ashes upon their heads, And fell down "
        "flat to the ground upon their faces, and blew an alarm with the "
        "trumpets, and cried toward heaven. Then Judas appointed certain men "
        "to fight against those that were in the fortress, until he had "
        "cleansed the sanctuary. So he chose priests of blameless "
        "conversation, such as had pleasure in the law: Who cleansed the "
        "sanctuary, and bare out the defiled stones into an unclean place. "
        "And when as they consulted what to do with the altar of burnt "
        "offerings, which was profaned; They thought it best to pull it down, "
        "lest it should be a reproach to them, because the heathen had "
        "defiled it: wherefore they pulled it down, And laid up the stones in "
        "the mountain of the temple in a convenient place, until there should "
        "come a prophet to shew what should be done with them. Then they took "
        "whole stones according to the law, and built a new altar according "
        "to the former; And made up the sanctuary, and the things that were "
        "within the temple, and hallowed the courts. They made also new holy "
        "vessels, and into the temple they brought the candlestick, and the "
        "altar of burnt offerings, and of incense, and the table. And upon "
        "the altar they burned incense, and the lamps that were upon the "
        "candlestick they lighted, that they might give light in the temple. "
        "Furthermore they set the loaves upon the table, and spread out the "
        "veils, and finished all the works which they had begun to make. Now "
        "on the five and twentieth day of the ninth month, which is called "
        "the month Casleu, in the hundred forty and eighth year, they rose up "
        "betimes in the morning, And offered sacrifice according to the law "
        "upon the new altar of burnt offerings, which they had made. Look, at "
        "what time and what day the heathen had profaned it, even in that day "
        "was it dedicated with songs, and citherns, and harps, and cymbals. "
        "Then all the people fell upon their faces, worshipping and praising "
        "the God of heaven, who had given them good success. And so they kept "
        "the dedication of the altar eight days, and offered burnt offerings "
        "with gladness, and sacrificed the sacrifice of deliverance and "
        "praise. They decked also the forefront of the temple with crowns of "
        "gold, and with shields; and the gates and the chambers they renewed, "
        "and hanged doors upon them. Thus was there very great gladness among "
        "the people, for that the reproach of the heathen was put away. "
        "Moreover Judas and his brethren with the whole congregation of Israel "
        "ordained, that the days of the dedication of the altar should be "
        "kept in their season from year to year by the space of eight days, "
        "from the five and twentieth day of the month Casleu, with mirth and "
        "gladness."
    ),
    "2 Maccabees 1:18": (
        "Therefore whereas we are now purposed to keep the purification of "
        "the temple upon the five and twentieth day of the month Casleu, we "
        "thought it necessary to certify you thereof, that ye also might keep "
        "it, as the feast of the tabernacles, and of the fire, which was "
        "given us when Neemias offered sacrifice, after that he had builded "
        "the temple and the altar."
    ),
}
